name: Build

on:
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Use GitVersion
      run: |
        dotnet tool install --global GitVersion.Tool
        dotnet-gitversion /output buildserver /nofetch
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack 
      run: dotnet pack --configuration Release --no-build
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Upload NuGet
      run: dotnet nuget push --source https://nuget.pkg.github.com/twsouthwick/index.json -k ${{secrets.GITHUB_TOKEN}} **/*.nupkg 
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: |
          **/*/bin/Release/*.nupkg
          **/*/bin/Release/*.snupkg
